### PR TITLE
Use uppercase for Sponge dropdown and switch to SVG Spongies

### PR DESCRIPTION
**Pull request by stephan-gh**
We seem to use SPONGE in uppercase almost everywhere together with Montserrat Bold. I personally think it looks much better in uppercase than it looks right now (in title case), so I attempted to change it and it looks quite nice.

| Current | Uppercase |
| --- | --- |
| screenshot_20161012_124146 | screenshot_20161012_155712 |

I've also removed the text from the logo image, made it normal HTML text and changed the Spongie marks to use SVG vectors ([which should be fine for all modern browsers](http://caniuse.com/#feat=svg)) for improved rendering on devices with higher resolutions.
### Demo

_Demo page current unavailable_

Tested on latest Firefox (Windows/Linux), Chrome (Linux), IE (Windows) and Safari (iOS 10)

### CODE REVIEW

**Comment by jamierocks** [comment]
SVG: Good
Uppercase: eww

**Comment by parlough** [comment]
Switching to SVG Spongies is a good choice, but I'm not a fan of the uppercase "Sponge" either.

**Comment by windy1** [comment]
I am personallly a fan of the old font. The spacing on the current one is weird too.

**Comment by stephan-gh** [comment]
@windy1 Spacing should be fixed on the demo now, I left some old code in that broke it.

**Comment by Zidane** [comment]
@Minecrell 

I think that is what this has been missing. Now, this is identical to our appearance publicly.

**Comment by Zidane** [comment]
@jamierocks @Meronat @windy1 

Our official logo and branding has it uppercase. It is our identity. This change aligns the visual representation of the homepage with this.

@Minecrell 
This needs to be changed elsewhere.

**Comment by ryantheleach** [comment]
I like the Title case version better, but if it means fitting with what already exists then there is no other choice unless we want to change it across the board.

**Comment by stephan-gh** [comment]
If necessary, I can easily revert this to title case with a one line change.

@Zidane 
I'm going to port the changes to the other sites once this is merged.

**Comment by progwml6** [comment]
code/changes are fine, however i'd like a final say on the titlecase/uppercase from @Zidane before merging this

I personally prefer title case

**Comment by jamierocks** [comment]
I also prefer titlecase.

**Comment by windy1** [comment]
I also prefer titlecase.

**Comment by Zidane** [comment]
I completely respect the opinions above and I can see the arguments for titlecase but our branding is clear and anything we've shown to the masses always has had it as uppercase (our logo, our Minecon representation). This situation would be no different and therefore needs to be uppercase as well.

**Comment by windy1** [comment]
@Minecrell Can you please port these changes to Ore when you get a chance?

**Comment by stephan-gh** [comment]
@windy1 I'll take a look soon.

@progwml6 Any idea why the homepage isn't serving the SVGs? The page updated but the SVGs return 404.

**Comment by jamierocks** [comment]
Sounds like Docker hasn't copied some assets...

**Comment by progwml6** [comment]
@Minecrell should be fixed now

**Comment by lukegb** [comment]
You can't add assets and expect them to be served immediately. You go transiently via the state of having a mix of the old version and new version of the deploy, so you've gotta be careful to make sure that the new version can serve the assets the old version wants and vice versa.

**Comment by lukegb** [comment]
(That said: the duration that this happens will be less, soon™️)

**Pull request merged**
