### PR TITLE
Update several references to Minecraft to specifically refer to the Java Edition.

### PR DESCRIPTION
**Pull request by JBYoshi**
**SpongeHome** | [SpongeDocs](https://github.com/SpongePowered/SpongeDocs/pull/626)

Since the Better Together update was released for the Bedrock editions of Minecraft (mobile, Windows 10, and now console), the name Minecraft now refers to those Bedrock editions. I've updated the references in SpongeHome to refer to the Java Edition specifically.

I didn't update all the places; things like "Minecraft community" are left intact, and I've also left spots intact when it's already been made clear that this is for the Java edition.

### CODE REVIEW

**Review by ST-DDT — APPROVED** [review]

**Review by kashike — APPROVED** [review]

**Comment by jamierocks** [comment]
To be honest, I'm not sure I agree with these changes - I think anyone remotely familiar with Sponge will already know, or assume, that it is for what is now Java Edition.

The other thing to consider, is that Sponge (as far as the API goes) is not really tied to any implementation (it is kinda linked to MC version - however, according to the Better Together eventually the releases will be syndicated), and could (although have fun anyone who tries) be used on a Bedrock server impl. Not that that would be an official Sponge impl.

I think the Sponge leadership need to decide on whether SpongeAPI is tied to a Minecraft 'edition'. I see no reason why it should, if the two versions (Java and Bedrock) are going to be one-to-one at some point. Obviously though, its not a decision for me.

**Comment by Spongy** [comment]
A preview for this pull request is available at https://spongy.github.io/SpongeHome-PRs/136/.

Here are some links to the pages that were modified:

- modified: https://spongy.github.io/SpongeHome-PRs/136/
- modified: https://spongy.github.io/SpongeHome-PRs/136/sponsors

**Comment by JBYoshi** [comment]
@jamierocks 

> I think anyone remotely familiar with Sponge will already know, or assume, that it is for what is now Java Edition.

I completely agree. However, not everyone knows about Sponge before visiting its website. This is meant to make that clear to casual Internet surfers right out of the gate.

**Comment by JBYoshi** [comment]
@SpongePowered/developers Input wanted concerning jamierocks’ comment above.

**Review by vectrixdevelops — APPROVED** [review]

**Comment by jamierocks** [comment]
Merged with https://github.com/SpongePowered/SpongeHome/commit/d2d219706b8c2e7ea53b2e48924814483fc88197 👍

**Pull request closed without merging**
