### PR TITLE
Fix Retina displays

### PR DESCRIPTION
**Pull request by jamierocks**
Just need @kenzierocks to test.

https://rawgit.com/jamierocks/SpongeHome/feature/retina/index.html

### CODE REVIEW

**Comment by Tzky** [comment]
My guess is that not only the browsers content is scaled but the wohle desktop. So setting the scale for the page itself won't work out well, because everything is scaled.

**Comment by jamierocks** [comment]
So we'd have to scale the website down then?

**Comment by Tzky** [comment]
yes, but that's a hacky solution. I'd pefer to not do it this way.

**Comment by jamierocks** [comment]
Hmm, not sure how to go about his without badgering other people to test - so I'll leave this to someone with a retina display to fix ;)

**Pull request closed without merging**
