### PR TITLE
REST API

### PR DESCRIPTION
**Pull request by jamierocks**
## Routes
- /api/v1/announcements
- /api/v1/announcement/:id
## Usecase
- Homepage (replaces horrid current solution)
- Future PR(s) (top secret :p)
## Running Instance

This PR is currently running on my staging instance of SpongeHome over at https://www-sponge-staging.jamierocks.uk/
## Notes

There is definitely more routes that the API can have, however I am of the opinion that at the current time this PR should not facilitate such routes.

### CODE REVIEW

**Comment by progwml6** [comment]
if we are doing a rest api I would reccomend using something like  [postman](https://www.getpostman.com/) for testing it

**Comment by MichaelHillcox** [comment]
@jamierocks Why /v1/ surely that is just going to make it more annoying for anyone using the api once you change over to /v2/ especially if their is little changes that could have been changed inline with /v1/ usage. Plus the correct way to do something like this is to just use /api/ and support a depreciated message if and when its needed.

**Comment by jamierocks** [comment]
> more annoying

I'm not all too sure how you got to this, but I'm going to assume you don't understand why the route is versioned, and what happens if and when we make v2.
1. The route is versioned as so that we don't break people's applications.
2. Firstly if and when v2 is made v1 won't just disappear. 

IMO it is far more annoying (on an user's standpoint) to make breaking changes without versioned routes, no?

> correct way

There is no definitive way of doing this, however versioning the routes does seem to be the trend currently and for good reason (touched on above).

**Comment by MichaelHillcox** [comment]
@jamierocks Alright, Sorry If I didn't pose it enough as a question. Just wondering on the reasons behind it. Thanks for explaining that :)

**Comment by jamierocks** [comment]
That's alright ;)

**Comment by jamierocks** [comment]
This is probably better off in a larger pr exposing more api routes. Closing.

**Pull request closed without merging**
