### PR TITLE
Readability, layout and a little bit of everything

### PR DESCRIPTION
**Pull request by MichaelHillcox**
Added some vital spacing,
Fixed up navigation to follow forums layout, #3 
Made dropdown icons follow forums ones ( mostly ), #3 
Made some background images darker to help with readability, #6 
made announcements font a little smaller, #6 
Add much better quality sponsor icons, #1 
Made social media icons a little smaller too.

Hopefully this should give you a helping hand with getting the page done sooner :) I would also suggest pulling in https://github.com/SpongePowered/SpongeHome/pull/8 request to fix up the deprecated tags.

### CODE REVIEW

**Comment by Zidane** [comment]
@Owexz 

https://htmlpreview.github.io/?https://github.com/MichaelHillcox/SpongeHome/blob/master/index.html

For reference for reviewers.

First off, thanks a ton for this. Really appreciate it. Your changes look good and if I hadn't taken a dose of NyQuil for my cold I'd put together a series of adjustments. Definitely a step in the right direction.

**Comment by Grinch** [comment]
Some general feedback...

#### Navbar

"About" needs to be the last one (furthest right).

#### Positioning

Announcements needs to be front and foremost above all else. If I'm going to a software's website I want to see the latest news front and foremost along with downloads. 

#### Pictures

Need some sort of visual identification when hovering over images such as the sponsor logos or the logos for SpongeAPI|Vanilla|Forge

#### Downloads

SpongeAPI should be the furthest left.
The 'Spongie' icons are a bit repetitive 

That is all for now. Will give more feedback when I have it.

**Comment by MichaelHillcox** [comment]
I'm really happy to hear that you both like it. I've been watching sponge for some time and I thought I could put my years of web design experience to good work for an awesome cause. I'll fix up your adjustment and update the pull. It think I can do that. I forget :P

**Comment by MichaelHillcox** [comment]
I've added a huge amount of improvements to the looks and addressed the issues @Grinch had. I've also sorted the issues #3 #11 #10 #1. I've improved all of the responsiveness for the home page and i've made the logo nav the same as the forums. I've also fixed the responsiveness for the main navigation. I've added a menu icon and improved its styling. 

I've switch out what icon font we are using and I've also sorted out the css files. I am now using sass but the original css is still there and if you want to use my sass but in css then put the .min.css through a css tidier. If you are using sublime or atom then they both have great sass auto compilers on save. 

Hope you like it. 

@Zidane I think you will like this one just as much :) also https://htmlpreview.github.io/?https://github.com/MichaelHillcox/SpongeHome/blob/master/index.html#announcements does not quite render everything correctly but it gives it a damn good go. Have a look by downloading my repo and running it :)

**Comment by MichaelHillcox** [comment]
Merged https changes into my repo https://github.com/SpongePowered/SpongeHome/pull/12

**Comment by JBYoshi** [comment]
@MichaelHillcox Well that was fast :smiley: Should I close my PR then, or leave it open?

**Comment by gabizou** [comment]
Not to be nit picky, but one thing that I personally like in most websites is a bit of jquery to have animated "scroll to" nav points. I know @Mumfrey added some for my website, but I could very well see some being used for this instead of the "snapping" or "popping" that you usually get with static websites.

**Comment by Tzky** [comment]
Some feedback:
- I'd prefer plain white background on the downloads section 
- social media icon can get replaced with font awesome icons
- add twitch to social media icons
- offsite links are still WAY too big
- navbar needs yellow buttons like ore-staging, forums and docs (on the right)

**Comment by MichaelHillcox** [comment]
@gabizou Not nit picky at all. Its already there but the github html render ignores the javascript. if you run it locally you will see what it runs like.

@Tzky I have a cool idea for downloads but I do agree that it needs something different. I've removed font awesome and replaced it with fontello to make it match the forums but I like the idea of using that as the icons. I will get on that. Also I know what you mean by the offsite links. I'll fix them in a min.

@JBYoshi yeah it was a little. You can if you want to. Your call :)

**Comment by MichaelHillcox** [comment]
@gabizou I've put a version on my site so you can see how it functions. 
This is the site as of commit https://github.com/SpongePowered/SpongeHome/pull/9/commits/fcec303c964db6c9fce9f19263c962fcac22df1f note that this commit has a bug with the logo navigation. The background is on the wrong z-index.
http://michaelhillcox.co.uk/dev/sponge/

**Comment by jamierocks** [comment]
I think the SpongeVanilla/Forge/API logos are too faded.

**Comment by MichaelHillcox** [comment]
@jamierocks have a look here http://michaelhillcox.co.uk/dev/sponge/ then hover over one.

**Comment by jamierocks** [comment]
Yeah I meant too faded when your not hovering over them.

**Comment by MichaelHillcox** [comment]
@jamierocks https://github.com/SpongePowered/SpongeHome/pull/9/commits/852292f8ffffeed99b15b7a85d4f3a275deeba22

**Comment by jamierocks** [comment]
Ah fantastic - taking a look now.

EDIT: Perhaps a darker background will help matters?

**Comment by MichaelHillcox** [comment]
@jamierocks Amazingly no. It makes things worse. I've actually lighted the image up. I have an idea on how to fix it :)

**Comment by MichaelHillcox** [comment]
@jamierocks That should have fixed it. I've updated my site to https://github.com/SpongePowered/SpongeHome/pull/9/commits/ef711e049a0c262397f70c54e087dbe8eb249dfb http://michaelhillcox.co.uk/dev/sponge/

@Tzky I can add the buttons but it will mess with the navigation. Is there another way you could this I could add them in with out messing with the navigation. If I was to add the buttons it would impact on the responsive element of the header.

**Comment by Tzky** [comment]
Then just leave them alone for now. No need to fix everything in a single PR ;)

**Comment by MichaelHillcox** [comment]
@Tzky Haha, Yeah. Just hoping it will get merged at this point :)

**Comment by jamierocks** [comment]
You should use the blue Nitrous Networks logo - I think it works better.

**Comment by Owexz** [comment]
Given that this PR fixes and improves upon numerous aspects of the site, we will be accepting it as is. Any unresolved issues can be addressed in later PRs. 

@MichaelHillcox, your work is greatly appreciated, it is most certainly an improvement to the site.

**Comment by MichaelHillcox** [comment]
@Owexz Happy to help. Any more issues I will continue to help out and fix. I'll be keeping an eye on this for sure :)

**Pull request merged**
