### PR TITLE
Make sponsors more prominent on homepage

### PR DESCRIPTION
**Pull request by jamierocks**
Running on https://www-sponge-staging.jamierocks.uk/#page-top

### CODE REVIEW

**Comment by Tzky** [comment]
Hmm, i don't like the looks of this vertical bar (i'm aware that this bar is on the sponsors page...). What about showing all sponsors directly below the Sponge logo as a single row?

**Comment by windy1** [comment]
I personally do like the vertical alignment but I think different background should be used (maybe translucent?). Also the Sponge logo proportions are incorrect.

Edit: Just played around with the background a bit. Honestly I think no background on the sponsors looks best.

**Comment by Tzky** [comment]
Yep, if we're going vertical, then no background looks best. This would also apply for a horizontal row below our logo.

**Comment by jamierocks** [comment]
@windy1 `Also the Sponge logo proportions are incorrect.`
Where are you referring to?

**Comment by Tzky** [comment]
the main logo `spongie-mark-dark.png` is 256 high and 256px wide. When viewing it on 1080p with a website scale of 100% it gets streched and doesn't remain square.

**Comment by jamierocks** [comment]
@Tzky Ah - I see the issue, thanks ;)

**Comment by Tzky** [comment]
Merged in ded5234

**Comment by jamierocks** [comment]
/me feels great for updating www-sponge-staging from his phone

**Pull request closed without merging**
