### PR TITLE
Add ServerMiner to sponsors. Fixes #95

### LINKED ISSUE #95: Add ServerMiner.com to our sponsorship sections
We have a new sponsor coming onboard:

https://serverminer.com

Logo:  http://www.almuramc.com/images/Border.png

They need to be at position #4.

Please PM Dockter for additional details.

### PR DESCRIPTION
**Pull request by jamierocks**
https://github.com/SpongePowered/Ore/pull/132

### CODE REVIEW

**Comment by windy1** [comment]
Going forward we should try to keep Ore's sponsors updated as well whenever we are doing this. The sponsors can be changed quite easily in the configuration here: https://github.com/SpongePowered/Ore/blob/master/conf/application.conf.template#L83-L84 and logos are kept here: https://github.com/SpongePowered/Ore/tree/master/public/images/sponsors

**Comment by Dockter** [comment]
@windy1 should I be placing tickets on both repos?

**Comment by windy1** [comment]
Either that or we should just designate someone to be responsible for updating the sponsors community wide because often times I'm not keeping up with that side of things.

**Comment by jamierocks** [comment]
I don't mind keeping them up to date for both Home and Ore ;)

**Comment by progwml6** [comment]
Just one is fine with me if you mention updating all sites within the ticket . Other options include possibly creating a JSON on spongehome that ore reads so that we only need to update one location for sponsors

**Comment by jamierocks** [comment]
But it has been known for one service to be down and not the other, so it's probably best their in both.

**Pull request merged**
