### PR TITLE
Remove Vue and downloads page from SpongeHome

### PR DESCRIPTION
**Pull request by stephan-gh**
Originally I added the downloads page directly within SpongeHome for simplicity. It turned out that Vue development doesn't fit well into a Go-based and otherwise mostly static web page. The custom webpack setup in this repository is way too complicated and not really nice to work with.

I've moved the downloads page to a separate repository at [SpongePowered/SpongeDownloads](https://github.com/SpongePowered/SpongeDownloads) where the development server, hot reloading and many other things work out of the box.
Currentlly, there are no major functional changes yet but I took the time to do some major cleanup, and migrated it to Bootstrap 4.
There is a temporary test page available at https://www.spongepowered.org/downloads2/

I've also removed the other usages of Vue from the index page, specifically the announcements and downloads section. The downloads section wouldn't work at all without the other files from SpongeDownloads, and it didn't seem worth keeping Vue just for the announcements.

Instead, I've added the downloads section as static HTML and moved the announcements to a simple jQuery script. Should do the job for now, at some point we wanted to change the way the announcements are loaded anyway.

Will follow up with the needed changes for deployment of the new downloads page soon.

cc @jamierocks if you want to take a quick look at the announcement changes

### CODE REVIEW

**Comment by Spongy** [comment]
A preview for this pull request is available at https://spongy.github.io/SpongeHome-PRs/145/.

Here are some links to the pages that were modified:

- modified: https://spongy.github.io/SpongeHome-PRs/145/

**Comment by jamierocks** [comment]
Hey @Minecrell the announcement changes look fine at first glance. I have some plans that may improve the announcement stuff in the future, that I want to discuss with you at some point.

Though the new downloads page should mirror the existing page - the new one feels more blocky and boring.

**Comment by vectrixdevelops** [comment]
The styling could probably be improved to match what we already have IMO.

**Comment by jamierocks** [comment]
Styling is part of it (e.g. nice background, correct font for Sponge(Forge, Vanilla, API), etc) - but also content, such as the footer that is missing in the new version.

**Comment by stephan-gh** [comment]
I did change the background on purpose but if the consensus is that it looks bad without it, I can restore it. I personally prefer the more simple look of the new page.

Otherwise there is really not much different to the old page. Not sure what's supposed to be wrong with the font, it's exactly the same as on the old page. And otherwise most changes were probably made in Bootstrap 4 and not by me directly (e.g. the badges).

About the footer - I should probably add the copyright + Fastly logo back but otherwise I'm not sure how relevant it is on the downloads page. SpongeHome exists as the place to get information about the project, the downloads page exists to downloads builds. It was on the old downloads page mostly just because it was inherited by the template.

If anything, it would probably make more sense to have something like Ore's footer that points to places where users can get help if they run into problems (e.g. the forums, chat and issue tracker).

**Comment by jamierocks** [comment]
> I did change the background on purpose but if the consensus is that it looks bad without it, I can restore it. I personally prefer the more simple look of the new page.

IMO it looks pretty bland without something going on there.

> Not sure what's supposed to be wrong with the font

Ignore my point on the font, it is indeed Montserrat - just the weight has changed (nicer IMO anyhow, just used to seeing Montserrat with a bit of weight).

> If anything, it would probably make more sense to have something like Ore's footer that points to places where users can get help if they run into problems (e.g. the forums, chat and issue tracker).

Sure, honestly its mostly about having something there, else the page feels empty.

**Comment by stephan-gh** [comment]
@jamierocks Added back the background image and added the footer. Can you take another look?

**Pull request merged**
