### PR TITLE
Add JetBrains and YourKit as a Sponsor

### PR DESCRIPTION
**Pull request by vectrixdevelops**
JetBrains have requested to be shown as a Sponsor on the homepage, as per request by @Zidane 

This fits with the requirements stated here: https://www.jetbrains.com/company/brand/

sponsors

### CODE REVIEW

**Comment by jamierocks** [comment]
I'm sure JetBrains provided a sponsor pack to @Zidane, that will undoubtedly contain a much better sized image for the site.

**Comment by vectrixdevelops** [comment]
@jamierocks this seems to be what he forwarded to Inscrutable who forwarded me a link. It seems we are quite limited but, you may be right. There may be some more options.

**Comment by phit** [comment]
You seem to be allowed to crop quite a bit from bottom and top.

**Comment by vectrixdevelops** [comment]
I will try crop it a bit phit.

**Comment by Spongy** [comment]
A preview for this pull request is available at https://spongy.github.io/SpongeHome-PRs/137/.

Here are some links to the pages that were modified:

**Comment by progwml6** [comment]
Please follow the cropping guidelines linked to get the sizing as close as possible to the others

**Comment by vectrixdevelops** [comment]
I'm feeling like no matter what I try, their logo just does not fit under Sponsors.

Maybe, the homepage could do with an acknowledgements section. Then YourKit could be added their too?

**Comment by phit** [comment]
Doesn't look too bad if you just crop it to the same size as the others.
jetbrains


image

**Comment by kashike** [comment]
All that's required is the *IntelliJ IDEA* logo, not the *JetBrains* logo, which is much smaller: https://www.jetbrains.com/company/press/#product-logos

**Comment by Inscrutable** [comment]
From the original message from JetBrains, ``If you feel that IntelliJ IDEA has helped you a great deal, we'd be grateful if you could mention JetBrains' support for your project by placing IntelliJ IDEA logo on the project's website. Please, follow the link if you wish to choose the logo`` http://www.jetbrains.com/company/press/materials.html"  
ie. use the small Intellij IDEA logo from the bottom of the page. It's somewhat less hideous.

**Comment by vectrixdevelops** [comment]
New and improved (I think?)

sponsors

**Review by kashike — APPROVED** [review]

**Comment by stephan-gh** [comment]
Have you tried using the SVG version of the IntelliJ IDEA logo (it's in the ZIP)? Unless it looks worse for some weird reason, it would be preferred over the PNG version.

**Review by stephan-gh — APPROVED** [review]

**Pull request merged**
