### PR TITLE
Sponsors Page Redesign

### LINKED ISSUE #16: Add build instructions to readme
The readme is missing information about sass, we need to add build instructions.

### PR DESCRIPTION
**Pull request by MichaelHillcox**
Did fix up read me but i've move it over to a Sponsors redo for #14

### CODE REVIEW

**Comment by jamierocks** [comment]
I have a better fix for this, that is convenient on all IDEs ;)

**Comment by MichaelHillcox** [comment]
@jamierocks What are you doing? hehe. This is just the way I've always done it. You can set Sass to watch the files but its more work that it needs to be. Other IDE's like phpStorm etc. Know how to handle sass and will do all the work for you.

**Comment by jamierocks** [comment]
See https://github.com/SpongePowered/SpongeHome/pull/18 - It uses Gulp (much like the SpongeDocs).

**Comment by MichaelHillcox** [comment]
Ah, yes. I've commented. Not used Gulp before. Do you want to add some of my readme to yours so we can offer multiple ways to compile?

**Comment by MichaelHillcox** [comment]
Well thats a nice list of changes.

I've overhauled the design of the page but i have not changes the wording. This is something one of the @spongepowered team will need to do. 

This should solve #14 but not the wording. I've also merged in #19. 

#### This needs feedback

https://htmlpreview.github.io/?https://github.com/MichaelHillcox/SpongeHome/blob/master/sponsors.html

Link for reviewers. Please remember that page does not render javascript and sometimes does not display everything. Downloading a copy is advised.

**Comment by MichaelHillcox** [comment]
Fixed things up to make the brach merge nicely

**Comment by jamierocks** [comment]
You should probably squash all these commits.

**Comment by jamierocks** [comment]
The reason the sass had it's own folder was because usually people separate sass/sccs/less/etc into partials.

**Comment by MichaelHillcox** [comment]
@jamierocks I should... but I like showing whats going on. This is definitely a messy pull request but I want people to see that I moved from fixing the read me to doing up the sponsors page. I will squash them if the @spongepower guys want me to.

@jamierocks also yeah I know they do normally but one file does not warrant it. If it was 2 files then sure thats fine but not for one sass file :P

**Comment by jamierocks** [comment]
This pr has had it's intent completely changed - I'm of teh opinion you should have created a separate pr :P

That's not to say that there isn't going to be a future pr where they are split into partials.

**Comment by MichaelHillcox** [comment]
@jamierocks Ah, Yeah. I think I agree with you there. Anyway from what I can see I can't squash the commits. I think @spongepowered have to do it when they merge the changes.

**Comment by felixoi** [comment]
@MichaelHillcox Please fix it for mobile. the "Our Sponors" thing have to go at the end for mobile.
It's sticky at the right side at the moment.

**Comment by MichaelHillcox** [comment]
@Feeliiix Thanks for reminding me

**Comment by Tzky** [comment]
Looks good. I'd like to get some feedback from other devs first before merging this.

Also this needs squashing before merge... :P

**Comment by JBYoshi** [comment]
@MichaelHillcox To squash a set of commits, do an interactive rebase on the SpongePowered master branch, then set all commits (except the first) to `squash` instead of `pick`. Once the rebase is done, force push to your fork's branch.

**Comment by Tzky** [comment]
JBYoshi, you can just checkout the branch and then `git rebase -i head~<numberofcommitstosquash>`

Besides that we can do this too... I usually check any PR myself before pulling it in, so i need to clone it to my local workspace anyways.

EDIT: I just fetched this PR and it looks like it messes with the file structure of the project. I'm not happy with this yet :/

**Comment by Tzky** [comment]
I stripped the sponsor page changes from this PR and added it to #22.

**Comment by Tzky** [comment]
The changes to the sponsors page are now on master. If you feel that there's something else from this PR which should get onto master, let me know.

**Comment by MichaelHillcox** [comment]
@Tzky Thats looking great. I'll close this PR.

**Pull request closed without merging**
