### PR TITLE
Dockerfile

### PR DESCRIPTION
**Pull request by jamierocks**
@lukegb 

this might be horribly wrong, who knows? :P

### CODE REVIEW

**Comment by progwml6** [comment]
why not use one of the alpine based docker containers?

**Comment by jamierocks** [comment]
I haven't used golang:1.6.2-alpine because it doesn't have git

**Comment by progwml6** [comment]
It's easy to add git to alpine

**Comment by Zidane** [comment]
@jamierocks @progwml6 

What is the status of this? I want Home staged ASAP.

**Comment by jamierocks** [comment]
Teamspeak in 5 mins @zidane ?

**Comment by Zidane** [comment]
@jamierocks 

At work so nope lol. Won't be home for another 9 hrs.

**Comment by jamierocks** [comment]
Alright ;P Home now so can type it out quicker:

There are a couple issues with this, however @progwml6 also want to get it using alpine, etc.
When @progwml6 gets back I'll get the list finalised ;)

**Comment by progwml6** [comment]
It's almost done I spent several hours fixing it last night. I just need to put in some commands to run this as a normal user when I get home from work .

**Pull request closed without merging**
