### PR TITLE
[WIP] Use go-discourse

### PR DESCRIPTION
**Pull request by jamierocks**

### CODE REVIEW

**Comment by gabizou** [comment]
How can we be sure that go-discourse will be maintained with discourse updates over time? Not to be pessimistic, just wanting to know the details for longevity and maintenance of the website and dependencies.

**Comment by jamierocks** [comment]
Once I figure out what is wrong with it currently I plan to see if I can use gopkg.in.

But to be honest the only updates I see myself doing are ones as the Discourse API updates, any breaking ones will likely be owing to them.

**Comment by simon816** [comment]
Why not keep the files on this repo so anyone can update it when needed?

**Comment by jamierocks** [comment]
I figured that others might want to use the models, so having full models in a separate package seemed the best solution.

**Comment by stephan-gh** [comment]
We can always easily fork it if it becomes inactive, the only line that needs to be changed is the import of the package.

**Comment by windy1** [comment]
Ya know I'm not really sure consuming a simple RESTful API really warrants it's own project. I think this is something that should just be included in this project so it can
  A. Be tailored specifically to the needs of this project
  B. Maintained easily

I'm not all that familiar with Go but I imagine it's fairly trivial to digest JSON data.

**Comment by jamierocks** [comment]
With the maintenance thing, as long as discourse doesn't make breaking changes, there won't be issues - the site uses 2 routes.

As far as tailoring it to sponge's needs, I'm not really sure how you can do that when all go-discourse is is structs to represent discourse's api

**Comment by progwml6** [comment]
if we were to go the route of a library for this i'd also question why have code relating to getting the various json files from the API in this repo and not in the library itself

**Comment by jamierocks** [comment]
I had thought of that and it's something I'll probably do.

**Comment by lukegb** [comment]
Closing this out, since it's been a few months now.

**Pull request closed without merging**
