### PR TITLE
Display emojis in announcement titles

### PR DESCRIPTION
**Pull request by jamierocks**
Alternatively, you could process the announcement titles and replace with `` tags, but this is a simpler solution.

### CODE REVIEW

**Comment by Spongy** [comment]
A preview for this pull request is available at https://spongy.github.io/SpongeHome-PRs/162/.

Here are some links to the pages that were modified:

- modified: https://spongy.github.io/SpongeHome-PRs/162/

**Review by felixoi — APPROVED** [review]
Approved. I need to wait for sysops until I can merge this.

**Comment by jamierocks** [comment]
> 
> 
> Approved. I need to wait for sysops until I can merge this.

👍

**Comment by jamierocks** [comment]
While I believe this PR has merit, I've pushed this as much as I will - to clear down my open prs, I'm going to close this.

Feel free to merge this regardless, but I have no interest in making further changes.

**Pull request closed without merging**
