### PR TITLE
Very quick. Nothing changed. Commit history update

### PR DESCRIPTION
**Pull request by MichaelHillcox**
This is hugely an uncommon practise and upon that its an odd thing todo. Please feel free to ignore this completely and close it. but...

nothing has changed. It wont count me as writing all the code, it only updates my actual commits ( i've checked on my fork ) it wont add 122 commits. Its just how github is looking at the changes. All I've done is a if( name == "mine" ) then update the committer email address. I had it set to the wrong one and was stupid. 

Like I said feel free to reject it. It won't upset me but it almost does nothing other than updates my email on my commits and assigns them back to this account. ( its a gmail ) so it will never be getting changed again. 

Thanks :)

### CODE REVIEW

**Comment by MichaelHillcox** [comment]
Wow, Sorry, so much, Just saying sorry now instead of later :). Please don't hate me <3

**Comment by jamierocks** [comment]
We're not going to rewrite history for that. I'm sure this will be closed as soon as someone with access is around.

**Comment by MichaelHillcox** [comment]
@jamierocks I know. You don't get if you don't ask.

**Comment by simon816** [comment]
@MichaelHillcox You can re-assign your email to your github account by verifying it on your account settings
https://github.com/settings/emails

**Comment by MichaelHillcox** [comment]
@simon816 No longer have access to said email

**Comment by progwml6** [comment]
merging this in would just put it on top of the current history not change your email, and i'm not doing force pushes in master to change the history

**Comment by JBYoshi** [comment]
@MichaelHillcox You can add an email address without verifying it if you want to keep those commits associated with your GitHub account.

**Pull request closed without merging**
