### PR TITLE
Use Gulp to compile sass files

### PR DESCRIPTION
**Pull request by jamierocks**
## Changes
- Add Gulp and the ability to compile the sass files
- Add build steps on readme
## Thoughts
- Use gulp-webserver

### CODE REVIEW

**Comment by MichaelHillcox** [comment]
Can you make the Gulp compile the css into compressed?

**Comment by jamierocks** [comment]
Yeah it does ;)

**Comment by MichaelHillcox** [comment]
@jamierocks can you set that to be default?

**Comment by jamierocks** [comment]
I have it separated into 3 tasks: sass, build and watch.

sass just builds the css file.
build depends on sass and makes the compressed version.
watch depends on build and runs build whenever changes are made.

The default task is build. ;)

**Comment by MichaelHillcox** [comment]
Awesome :)

**Comment by Tzky** [comment]
Closed with a02aeecd15c25ec4b4f96c11c4c27a52aec78a45

**Pull request closed without merging**
