### PR TITLE
Major refactor and cleanup

### PR DESCRIPTION
**Pull request by stephan-gh**
- Refactor setup to support more pages
- Update and cleanup various things
- Major cleanup and several fixes for the nav bar
- Change nav bar to use on-brand colors
- Display correct page in dropdown
- More changes I can't remember

**Needs some testing on different browsers, the nav bar might not work on all of them.**
**Demo site:** https://dev.minecrell.net/sponge/

### CODE REVIEW

**Comment by Tzky** [comment]
I noticed a small visual annoyance when viewing with my mobile device. Note the different padding of the dropdowns:

screenshot_2016-06-24-12-40-56

**Comment by stephan-gh** [comment]
The top padding in the dropdown?

**Comment by progwml6** [comment]
I took a quick look at the code and it looked to be in good shape, I'll do some browser testing over the weekend

**Comment by Tzky** [comment]
Minecrell: space to the left and right sie of the screen

**Comment by stephan-gh** [comment]
Oh!

**Comment by stephan-gh** [comment]
@Tzky Should be fixed.

**Comment by Tzky** [comment]
Yep, the last push fixed it for me.

**Comment by jamierocks** [comment]
Updated to latest master -> https://github.com/jamierocks/SpongeHome/tree/refactor

**Comment by Tzky** [comment]
@Minecrell 
Is this done or at least ready for merge? If yes, i'll get this into master asap.

**Comment by Tzky** [comment]
Merged in cbe6464.

**Pull request closed without merging**
