### PR TITLE
Update Sponsors

### PR DESCRIPTION
**Pull request by vectrixdevelops**
- Removes old Sponsor Images.
- Adds MC Server Hosting as a Sponsor.

sponsors

### CODE REVIEW

**Comment by Spongy** [comment]
A preview for this pull request is available at https://spongy.github.io/SpongeHome-PRs/148/.

Here are some links to the pages that were modified:

**Comment by jamierocks** [comment]
Looking at that on mobile - the MCServerHosting and Apex logos look low-res, do they not provide decent res images in their sponsor kit?

**Comment by vectrixdevelops** [comment]
@jamierocks Unfortunately not I believe.

**Comment by vectrixdevelops** [comment]
Oops, I sort of broke this PR. New one is here https://github.com/SpongePowered/SpongeHome/pull/149

**Pull request closed without merging**
