### PR TITLE
Start working on #52

### PR DESCRIPTION
**Pull request by jamierocks**
This PR intends to rectify some (if not all) of the issues mentioned in #52.
## Minor off-brand issues
- [x] Some components (notably the "get sponge" buttons, and some body text) use `#2c3e50` which is an off-brand colour which is basically a very dark navy blue, this should be replaced with 20% grey (`#333333`)
- [x] Some components (the "get sponge buttons") use `#1a242f` as a hover colour with `#161f29` border, this should again be a mid grey or an on-brand colour such as `#f8ce0f`
- [x] Some components (notably some titles, the word SPONGE on the main landing page, and the hover colour for some items such as the links on the home page) use `#000000` which is off-brand and should also be a dark grey such as `#2b2b2b` to match the spongie mark
- [x] Hover colour for the Interested in Sponsoring sponge? button uses off-brand `#cc8800`
- [x] The yellow "sun rays" image on the main splash is generally the wrong hue and doesn't match the brand yellow. The hue should be corrected to 49° to match the branding, or a different image should be used. Here is a colour-corrected version.
## Some other minor aesthetic/accessibility notes
- [x] Link text for github is "GitHub" on the strap links and "Code" on the pulldown
- [x] Link text for documentation is "Docs" on the strap links and "SpongeDocs" on the pulldown
- [x] Pulldown icons vary in size, some are 14x15, some are up to 19x15. This makes the alignment of the pulldown text very uneven.
- [x] No alt text for spongie logo on home page
- [x] No alt text for sponsor logos on sponsors page
## Some aesthetic considerations which are merely my opinion:
- [x] The spongie mascot being animated feels tacky, I know it was part of the original home page but I would question its inclusion on the new page, which overall has a much more professional and less rushed appearance. The animated spongie undermines this somewhat in my opinion.
- [x] The social buttons look a bit untidy compared to their strap link counterparts. Maybe make them all grey to match?
## Live Version

Unfortunately my instance of SpongeHome is currently being used for a separate PR (#51).

### CODE REVIEW

**Comment by Tzky** [comment]
Uhm, why did you merge this @progwml6? It obviously wasn't done yet...

**Comment by progwml6** [comment]
@Tzky it was left in a mergable state according to @jamierocks

**Comment by Mumfrey** [comment]
Wait so if this was merged already does that mean the other unchecked items aren't being fixed?

**Comment by Tzky** [comment]
I made further changes in 37b7fce and ticked the checkboxes accordingly.

**Comment by jamierocks** [comment]
@Mumfrey prog wanted to merge it so he could do some stuff

**Comment by Tzky** [comment]
The width of the pulldown icons was resolved in bd2f430. The list should be complete now.

**Pull request merged**
