### PR TITLE
Modding API -> Plugin API

### PR DESCRIPTION
**Pull request by jamierocks**

### CODE REVIEW

**Comment by MichaelHillcox** [comment]
Why plugin?

**Comment by gabizou** [comment]
Why?

**Comment by jamierocks** [comment]
I seem to recall there being a discussing of this.

It's called a plugin API rather consistently through the SpongeDocs and on the GitHub repo's description.

**Comment by Tzky** [comment]
There are plans to expand SpongeAPI to the client, so i'd keep modding API.

**Pull request closed without merging**
